### ISSUE TITLE
How to get occlusion of 3D objects by the real world (Hololens 2)

### ISSUE THREAD

**Issue by marcojez** [maluoi/StereoKit#100]
Hi everyone,
I'm building an MR app with StereoKit on Hololens 2, but I can't figure out how to make my 3D objects be occluded when they are behind real-world surfaces. I'm new to both Hololens and Stereokit, so I might be missing something obvious.
Any hint?

Cheers,
Marco

**Comment by maluoi** [comment]
Hey Marco!

Right now, this a limitation from the OpenXR side! OpenXR doesn't currently have any finished API for retrieving detailed information about the environment, as far as I'm aware of. There is a preview extension, [XR_MSFT_scene_understanding_preview2](https://microsoft.github.io/OpenXR-MixedReality/openxr_preview/specs/openxr.html#XR_MSFT_scene_understanding_preview2) that is available in Microsoft preview runtimes, but I haven't checked it out well enough to know if it would work in this case. "Scene Understanding" is conceptually more about high-level representation rather than raw depth/mesh data that's good for occlusion.

There's also the [Scene Understanding SDK](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/scene-understanding-sdk) for C#, but StereoKit v0.2 doesn't play _quite_ well enough with the SDK's use of System.Numerics to make that a good solution yet. The OpenXR scene understanding preview is based on this SDK as far as I understand, so I'm still uncertain if it provides an occlusion-focused mesh.

For StereoKit v0.3 (which is allllmost done), I've replaced the existing math structures with System.Numerics, so it'll play much better with stuff like the Scene Understanding SDK, and get a nice performance bump too. Scene understanding will be one of my higher priorities after v0.3 ships, and will probably find itself in v0.3.1, or v0.3.2, even if that functionality is still in a preview state by then.

I hope that's helpful! :)

**Comment by marcojez** [comment]
Hi Nick,

thank you for your explanation. According to Microsoft's Mixed Reality documentation, the API that seems to be more suited to the task is the Spatial Mapping API, rather than the Scene Understanding SDK. However I can't see it being exposed in OpenXR (it doesn't seem to be part of XR_MSFT_scene_understanding_preview2). So I guess I'm out of luck for now.

Unfortunately, mixing holograms with the real world is a major requirement for my application, so I guess I'll have to stick with Unity for a little longer. That's a shame, as Unity is quite overkill for my purpose.

I'll continue to follow the development of StereoKit, waiting for Microsoft to release a new OpenXR extension...

Thanks again!

**Comment by maluoi** [comment]
I dug into this a bit further, chatted with come co-workers. Scene Understanding -does- provide a mesh that would work, but the refresh rate is not fast, so they didn't recommend it. They did point out the `SpatialSurfaceObserver` that UWP provides could still work just fine! And it... almost does!

I wrote up an implementation of this [here as a gist](https://gist.github.com/maluoi/71cca9955251d3f34243ea34ec107738). The problem I ran into was synchronizing coordinate spaces, I thought OpenXR's Spatial Graph interop would work, but it needed the Spatial Anchor interop instead, which I haven't implemented yet :( Definitely gonna make sure that's in for v0.3!

Instead, it uses a hack that requires the user to stand still during initialization. Not a production ready solution, but can work as a placeholder. There's a few extra details about the hack in the code. But I won't be even remotely offended if you don't want to use it though! :)

Using it is pretty simple, here's a red wireframe occlusion mesh:
```CSharp
OcclusionMesh occlusion = new OcclusionMesh(Color.HSV(0,1,1));
occlusion.Material.Wireframe = true;

while (StereoKitApp.Step(() => {
	occlusion.Step();
}));
```

Changing that to solid black is pretty trivial, and should behave the way you're looking for :)

**Comment by marcojez** [comment]
Hey Nick, thank you very much for making your hands dirty with this issue! I'll make sure to give your code a try ASAP and get back to you with the results.

**Comment by maluoi** [comment]
I have a more complete sample for this with the current v0.3. This should properly sync the spaces together as well!

See this code for the SpatialSurfaceObserver -> StereoKit implementation:
https://github.com/maluoi/StereoKit/blob/master/Examples/StereoKitTest/Tools/OcclusionMesh.cs

And then this code for how to use it:
https://github.com/maluoi/StereoKit/blob/master/Examples/StereoKitTest/Demos/DemoWorldMesh.cs

**Comment by marcojez** [comment]
Hi Nick,
thanks for the update. I've tried it, and it seems to work. Does the requirement of standing still at initialization time still apply?

**Comment by maluoi** [comment]
This code does now use the proper spatial anchor interop extension, so you no longer need to stand still for this to work :) Looks like I may still have some comments leftover, I'll update those, but this should work properly!

One thing to watch out for though, I don't think this code really nails down the correct behavior when the device completely loses tracking and then regains it. There's definitely some improvement to be made there, but it's completely on the Windows.Spatial side of the code.

**Comment by marcojez** [comment]
Hi Nick,
after extensive testing, I can say that the proposed solution doesn't work correctly. Most of the times, the occlusion mesh doesn't match the real geometry. There is some offset/rotation that appears to be different at each run, but then stays constant while running. When the occlusion mesh gets updated, it actually reacts to changes in the environment, but it is still displayed in the wrong location/orientation.

Also, the occlusion mesh doesn't "follow" you as you move away from the initial location: it gets updated only around the initial point.

I've tried to recreate the OcclusionMesh class from scratch to rule out potential bugs in the code, but I get the same result in my code. So there's something wrong with the logic itself... Maybe it's the spatial anchor thing? I've also tried to implement the same logic that you can find in Microsoft's spatial mapping samples, where they don't user anchors, but there is always one piece missing: at some point I need to call the GetStationaryCoordinateSystemAtTimestamp(TimeSpan) method, passing the predicted frame timestamp as argument, but I don't know where to get that value.

Any ideas?
