### ISSUE TITLE
Discussion forum

### ISSUE THREAD

**Issue by wimachtendink** [maluoi/StereoKit#121]
Hello

Recently there's been a lot of issues which might be better suited for something like discord, slack, reddit, or a forum.

If setting something like this up would be too much work I wouldn't mind volunteering a bit :)

**Comment by maluoi** [comment]
Much of that has been using GitHub's new Discussions feature, which I think is pretty handy! I do like having a searchable record of feedback and assistance, since that has much more longevity than Discord/Slack style chats.

However! I did actually start up a [Discord channel](https://discord.gg/5fynxXw7) very recently, which I will promoting on StereoKit's home GitHub and Website pages when v0.3 comes out :) You're totally welcome to join in over there!
