### ISSUE TITLE
TextStyle let's fonts behave weird

### ISSUE THREAD

**Issue by TopperDEL** [maluoi/StereoKit#122]
If I just add that line in a static constructor, all fonts of the UI react weird even if the style is not used anywhere:

`_style = Text.MakeStyle(Font.FromFile(@"c:\windows\fonts\calibri.ttf"), 3*U.cm, Default.MaterialFont, Color.White);`

The text on a button then looks like this:

![image](https://user-images.githubusercontent.com/1833242/107956682-c88b7d00-6f9f-11eb-95db-27354273c5ab.png)

**Comment by TopperDEL** [comment]
The font-style works when using Text.Add and Text.Size, but here I also do not get special characters rendered on a Hololens (like ö,ä,ü and such). On UWP on my PC, they get rendered.

The weird texts as seen above happen ob both PC and Hololens, though.

**Comment by maluoi** [comment]
The garbled text issue there is from the way the Material is shared! In this case, the same Material is now used from two different fonts, so the atlas texture is replaced with a different layout. Use `Default.MaterialFont.Copy()` for this one!

Seems like it could be a good idea on my side to revise the API so that doesn't happen! I'll definitely look into doing that.

Haven't gotten to the HoloLens special characters yet, but I'll try and check that out next :) It's technically a holiday today, so I may or may not save that part for tomorrow~

**Comment by TopperDEL** [comment]
You're right - copying the Material solves that issue. I'll count that as an error on my side. :)

**Comment by maluoi** [comment]
I did dig into the other issue on UWP today, and I can definitely recreate it! I understand roughly what it's about by this point, but I'm uncertain exactly how to fix it so far.

The core issue is that my text system currently only renders one-byte/ASCII text. Under character 127, ASCII seems to be pretty universally the same, but above 127 you get into murky territory with code pages and character encodings. The change I just made recently for you was to expand my character atlas to include 127+ characters that are moderately standard.

C# just handles text using UTF-8, one byte for characters under 127, and two bytes for characters over 127. The difference here is how these strings get treated when going from C# to the native C++ code. On Windows desktop, it seems perfectly happy to store/convert umlauts as 127+ ASCII characters, but Windows HoloLens is just passing along multi-byte UTF-8 instead. I'm not sure why they would behave differently here, but I'm guessing this is the OS rather than the architecture.

The correct solution is still to properly support UTF-8! I'll keep peeking around for a quick hack, since the full UTF-8 rendering thing will still be a lot of work. But this means I may need to get to that a little sooner than I was initially thinking!

**Comment by TopperDEL** [comment]
Thanks for the explanation! I'm feeling a little bad that I only throw problems at you and cannot help you out. I assume, passing strings to the C-layer is not the main problem - but rendering the characters is, right? Because passing them correctly via the managed/unmanaged-border should be only a matter of setting some PInvoke-attributes.

If I may help with anything, let me know!

**Comment by maluoi** [comment]
Surfacing these problems and working through them is already plenty of work, and I'm extremely glad to have your feedback! I try my hardest to put StereoKit through its paces with tests and my own projects, but it's _very_ helpful to hear what issues you're running into as well.  So, you're helping plenty already! Thank you :)

Please don't mind me getting a little into the weeds of the issues here, I don't mean to burden you with details! Sometimes those details are interesting, so I just like to share. But also, this is a really helpful way for me to work through the problems, and keep a good record for when I swap between tasks.

I was actually expecting the PInvoke attributes to correctly handle the 127+ characters! And it does seem to quite nicely on Desktop. You only really get Unicode and Ansi as options for that, so I figured it was pretty straightforward. My current guess is that either Windows HoloLens has a different definition of Ansi from Desktop, or perhaps that .Net Native may be converting and storing strings with a different encoding when building for ARM64.

Related to rendering larger character sets like UTF-8 I have to think about generating glyph atlases a lot more. For 256 characters, just slapping them onto a single texture at runtime is really trivial. But when doing the same thing for Japanese language support, suddenly things become much more complicated. I might need multiple atlas textures, or even compile-time glyph atlas rendering to make startup faster! I also do string parsing for things like word wrapping, alignment and sizing, and I haven't got that configured properly for UTF-8 multi-byte strings :)

**Comment by TopperDEL** [comment]
It's always interesting to hear of your thought, implementation details and problems! This widens my understanding and knowledge. So keep on going like this!
Unfortunately, this is another point where I cannot really help you. :)
