### ISSUE TITLE
Spatial Graph Bridge

### ISSUE THREAD

**Issue by sjando** [maluoi/StereoKit#151]
Seeing a warning about missing support for spatial bridge for when trying to use World.FromSpatialNode, and indeed SK.System.spatialBridgePresent reports false. This is using v0.3.1 on a HoloLens 2 with latest OS and XR_MSFT_spatial_graph_bridge listed as available in the OpenXR developer tools app. Spatial perception capability enabled in manifest.

Is there something else required for an app to enable the extension or otherwise opt-in, or is this an incomplete feature/possible bug?

**Comment by maluoi** [comment]
Thanks for pointing this one out! Looks like it's a bug with v0.3.1. I've tracked it down and fixed it, so it'll be in the next update :)

I'm planning on making a preview build for NuGet either this week or next. If this bug is a blocker for you, let me know and I'll make sure the build goes up this week!

**Comment by maluoi** [comment]
v0.3.2-preview.1 is available on NuGet, and contains the fix for this :) Closing this now, but please re-open if it gives you any trouble!
