### ISSUE TITLE
Manipulate Plane Model

### ISSUE THREAD

**Issue by cwule** [maluoi/StereoKit#169]
I am generating a plane model and would like to point it towards the user like a screen. However, I cannot manipulate the plane via UI.Handle("Plane", ref planePose, cubeBounds, true). And when setting the plane transform manually, it is always in the xz plane. Looking at the doc, I am wondering whether planes generated via GeneratePlane are only intended as floor (always xz plane) and cannot be manipulated like other objects?
And there is this really handy Plane class, which lets you set the normal (eg. from the object center to the user). Would be great if I can just set the plane model like this, is this possible?

**Comment by cwule** [comment]
A thin cube seems to do the trick.

**Comment by maluoi** [comment]
Yeah, the generated plane is currently XZ only in model space. You can use `Matrix` transforms to compensate for this without too much trouble, here's a quick example:

```CSharp
Model planeModel = new Model();
planeModel.AddSubset(
	Mesh.GeneratePlane(Vec2.One), 
	Material.Default,
	Matrix.R(Quat.FromAngles(-90,0,0)));

UI.Handle("planeHandle", ref meshPose, planeModel.Bounds, false);
planeModel.Draw(meshPose.ToMatrix());
```

I use `Model` here instead of a `Mesh`, largely because the `Model` will properly recalculate the `Bounds` taking into consideration the subset's transform. If Bounds aren't a concern, you can also mix Matrices like this:

`planeModel.Draw(Matrix.R(Quat.FromAngles(-90, 0, 0)) * meshPose.ToMatrix());`

You might also be interested in the [default quad mesh](https://stereokit.net/Pages/Reference/Default/MeshQuad.html), which I often use for occasions that require facing behavior!

**Comment by cwule** [comment]
Thanks, that is super helpful!
