### ISSUE TITLE
use PC's keyboard to send commands to HoloLens in StereoKit

### ISSUE THREAD

**Issue by abdullahthabit** [maluoi/StereoKit#170]
Hi nick,

I hope you're doing well. I am trying to use the Virtual input in the Windows Device Portal to send keyboard inputs to the Hololens, but with no success so far. I tested the Virtual input with Microsoft Edge on the Hololens and it works, but when I try to use it with my StereoKit app, I receive nothing. I  am working on the native side, and I tried using the "input_key(key)" function to check the status of the button pressed. I tried checking the Internet client and server capabilities but with no success. Any pointers to how to get this working? many thanks!

**Comment by maluoi** [comment]
Heyas! Thanks for the note.

My HoloLens is being fussy today, so I checked this out on the HoloLens emulator. I tested this with the Input control in the UI scene of StereoKitCTest, using the Device Portal's Virtual Input tool. It is behaving a little strange, sometimes I can see UWP sending keypress messages without any key code, sometimes it's sending the correct keys twice, and sometimes it's sending things as expected. Given the way this is showing up on my end, my guess is that either the virtual keyboard has some quirks in it, or is exploiting some edgier features that StereoKit doesn't account for.

Since you're doing native, I assume you're building from source. What version/branch of StereoKit are you using? v0.3.1 included a big re-work on how keyboard input worked behind the scenes, so make sure you're at least using that. Any other details you think might be helpful would be great as well!

**Comment by abdullahthabit** [comment]
Hi Nick,

Thanks for your reply. I am using an older version, I believe v0.3. I am mainly interested in physical key pressing events. I want to use it to send commands to the Hololens to excute some functions, like render some objects, record the poses ... etc so I guess {input_key} should be suffecient for what I need.

Thanks for the suggestion. I will upgrade to v0.3.1, but I was wondering did it work with you right off the bat using {input_key} or you had to do some extra work? I would like to see if I can replicate your findings. Thank you!

**Comment by maluoi** [comment]
v0.3.1 made keyboard interaction much more reliable across the board, so I think you'll see some results just by switching to the newer version! This didn't work right away for me with the Device Portal keyboard, I had to play a bit with window focus on my browser, but I didn't need to make any changes to the application for it to work.

I typically use a bluetooth keyboard when trying to do keyboard stuff on HoloLens, it's pretty reliable, and makes a lot of things nicer! It can definitely be worth investing in one. I also will often put small windows behind the start position with buttons that can be pressed, rather than using keyboard-based debug tools.

**Comment by abdullahthabit** [comment]
Ok, thaks Nick!
