### ISSUE TITLE
Texture created with TexFormat.Bgra32 fails under certain conditions

### ISSUE THREAD

**Issue by chitsaw** [maluoi/StereoKit#195]
Ran into an interesting issue while experimenting with the `Tex.SetColors(int, int, IntPtr)` API. Our raw image data is BGRA32, so I created a texture with `TexFormat.Bgra32`, followed by a call to `SetColors()` to set the texture's pixels. This all worked splendidly until I used an image of 512 by 512 pixels, which caused an exception to be thrown by `d3d_device->CreateTexture2D()` in `skg_tex_set_contents_arr()` (sk_gpu.h).

I believe the underlying issue is that `skg_make_mips()` doesn't handle the BGRA32 case, so no mipmaps get generated. It seems that mipmaps are only created if the image dimensions are powers of 2, so you won't always hit this issue. Additionally, we can easily work around this by creating the texture using `TexType.ImageNomips`.

**Comment by maluoi** [comment]
Okay, looks like the specific issue here should be pretty easy to fix! BGRA should work just as well as the other supported texture formats, and I can put in some better checks to prevent exceptions entirely.

Some additional questions, because I may want to understand a little better how you're using this.
- Do you need mip-maps on this texture, or were you simply using the defaults?
- Would mip-maps for non-power-of-2 textures be important in this scenario?
- Are you updating this image regularly, or is this a resource that you're just creating once and using as is? Generating mip-maps on a texture that gets updated frequently is something that probably should be avoided.

**Comment by chitsaw** [comment]
Answers to your questions:
- Do you need mip-maps on this texture, or were you simply using the defaults? _No, I was simply using the defaults_
- Would mip-maps for non-power-of-2 textures be important in this scenario? _No_
- Are you updating this image regularly, or is this a resource that you're just creating once and using as is? Generating mip-maps on a texture that gets updated frequently is something that probably should be avoided, but can eventually be more performant with additional work on StereoKit's side. _Yes, the intent was to update this image frequently (it is a basically a stream of images coming from the camera). I don't think we need mipmaps for this._

**Comment by chitsaw** [comment]
Some more context - basically the scenario was given a stream of bitmaps in BGRA32 format, we just wanted to draw the bitmaps on a simple plane mesh using the texture. And just to reiterate, no urgency to fix this from our perspective, as we have a simple workaround :-)

**Comment by maluoi** [comment]
Awesome, thanks a bunch for the details here! Fix will be in whenever I get to the next build :)
