### ISSUE TITLE
[Proposal] Updating the folder structure

### ISSUE THREAD

**Issue by DirkSonguer** [maluoi/StereoKit#2]
As I am going through the code, I would love to propose some (very opinionated) updates of the file structure of the project:

**Collect examples in their own topical subfolders with CPP and CS underneath**
Reason: This would give us the ability to add more focused examples as we go along.
- Create a /Examples folder in the root directory
- Add a folder for each topic, currently a /GettingStarted one and add simple README for folder
- Move /StereoKitCTest to /GettingStarted/CPP
- Move StereoKitTest to /GettingStarted/CS

**Move topics in the core to respective subfolders**
Reason: The current prefixes help to identify topics, however the number of files will grow and splitting them into concerns will keep the project manageable.
- Mirror the current VS project structure as folders by adding a /Platform folder and adding openxr.cpp and .h, win32.cpp and .h and win32_input.cpp and .h there
- Start creating topical folders for things that have more than 2 files, for example /Input or /AssetManagement

What do you think?

**Comment by maluoi** [comment]
> Move topics in the core to respective subfolders

I've left the C++ files in a single directory largely because this is how I've seen most C++ projects! If I had to guess why, I'd say it probably simplifies building under certain command line environments? But since Visual Studio lets you sort them into folders in its solution view, I don't feel like it really needs the matching folder structure. At some point I'd like to support other build systems, so maybe some more research is due here?

For C#, that's definitely a best practice, and I'm happy to stick to it there :)

> Collect examples in their own topical subfolders with CPP and CS underneath

I'd love fewer folders under the root directory, and this would be a great way to do it! I'm re-working a bit of folder structure as part of the multi-architecture branch right now, so I'll add some of this :)

I'm also a fan of a single example explorer (per language in this case), rather than multiple example projects! Especially if the content is going to be experienced on a headset or device, multiple applications can get a little cumbersome to switch in and out of. Sound reasonable?

**Comment by DirkSonguer** [comment]
> I'm also a fan of a single example explorer (per language in this case), rather than multiple example projects!

Example browser vs. individual projects depends. If examples are a collection of for example UI things, then they can be one big demo (see for example the big UWP Win UI component demo apps). If they show different things like "here is a demo for networking", "here is one for controller input", "here is one for foveated rendering", then I guess separate projects make sense. I also don't like if demo apps get too big, but that's subjective.

I think that can be decided as we go along, keeping big topics together as much as possible in one demo app.

> I've left the C++ files in a single directory largely because this is how I've seen most C++ projects!

I've been "brought up" with projects (Unreal engine and similar ones) that had concerns in their own subfolders. I prefer it because I don't need to open VS to understand the structure and can just navigate and use other editors quickly if I want to change just one file quickly and compile on command line. Again, very subjective. Currently it's still kinda manageable, so no huge deal yet.

**Comment by maluoi** [comment]
> I think that can be decided as we go along, keeping big topics together as much as possible in one demo app.

Sounds great to me!

> I prefer it because I don't need to open VS to understand the structure and can just navigate and use other editors quickly if I want to change just one file quickly and compile on command line.

Alright! If it's helpful, and you prefer to command-line compile with sub-folders, then that's good enough to allay my concerns :)

**Comment by maluoi** [comment]
https://github.com/maluoi/StereoKit/commit/7d8b8c75c2a19fd66de0e37b149531b24d4d0607 now uses an Examples folder for the StereoKitTest projects.
