### ISSUE TITLE
Force to start in steamvr?

### ISSUE THREAD

**Issue by andrewpros** [maluoi/StereoKit#339]
I have oculus desktop, but it seems there is no way to force it run thru steamvr?

**Comment by maluoi** [comment]
Which OpenXR runtime gets used by StereoKit depends entirely on which runtime the system recognizes as active. As a developer, you can't specify which runtime the app should use, this is the end-user's choice!

SteamVR does have an option in the settings that allows you to set it as the active runtime. Most runtimes will also prompt you and provide a shortcut to that setting when you start them up. I've also built [OpenXR Explorer](https://github.com/maluoi/openxr-explorer) with some tools for switching active runtimes via CLI or GUI, which can be a little nicer as a dev that likes to switch between runtimes a lot :) There's also a [powershell script](https://github.com/maluoi/StereoKit/blob/master/Set-OXR-Runtime.ps1) in this repo that can switch runtimes as well, but that was the precursor to OpenXR Explorer!

**Comment by andrewpros** [comment]
Thats not true, there are many games on steam that have both options, steamvr and oculus native, it is the end user choice the same way a dev can provide only one of them and will not work with others, even if it is the default in the system, just like forced steamvr usage on oculus setups.

Many steam games do have only steamVR mode, even if it is oculus headset and oculus set as the active runtime and it works.

And u dont need to change the system runtime at all, u just choose in what mode to run, if there is a choice that is.

But in this case, StereoKit app is the "game" and there is no way to force it to run ONLY thru steamVR and this is needed for overlay apps even if it is on oculus setup as oculus doesn't support overlays. And it is needed to use steamVR apis.

So guess what, i do use oculus and it is set as the active system runtime and yet, when i run a steamvr app i do not need to change anything in the system, i never needed to do it and i should not do it, this is the official recommendation.

So maybe i do not understand some things or how to achieve them, but why this was closed without any proper solution?

The question stands, how can i force SteamKit app to always run thru steamVR without any changes in the active system runtime like basically anything on steamvr. Do i need to do some integration maybe?

**Comment by maluoi** [comment]
I think I see a bit more of what you're getting at here! It's possible you're mixing up OpenXR, OpenVR (SteamVR's api), and VrApi (Oculus's API). What I said is true for OpenXR, and StereoKit is 100% OpenXR only right now. A lot of apps out there may still use the older APIs, and this can certainly mean you'll see apps that run exclusively on one runtime or the other.

Since OpenXR is an open standard API for all devices, the core concept is that it should not matter which runtime or headset it's running on, in the same way that OpenGL doesn't care if it's running on an Nvidia, AMD, or Intel card. To surface runtime specific functionality, these APIs use extensions that may or may not be present (hence OpenXR Explorer).

The _appropriate_ way to handle this is to look at the runtime's **capabilities**, and then ask the user to switch if it's not capable of core functionality. The user should still get to choose which runtime to use! For example of why this is important: Monado has overlay support, but if you lock the app to SteamVR, then Monado users will not be able to use the app despite being entirely capable of it. Similarly, if Oculus adds overlay support later, you'd have the same problem.

**Comment by andrewpros** [comment]
Ok, now i see, its there, in plain sight, but i do not got it the first time, StereoKit does support steamvr, but only thru OpenXR, so no steam overlay api.

Now that is interesting for steamvr overlays as OpenXR has only a preview overlay system extension, but sooner or later, there will be only OpenXR, so there is something to consider here using steam openVR.

Anyway thx for help.
